# Generated by Django 3.2.4 on 2021-07-15 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Pokedex', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='myuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_in_pokedex_created_by', related_query_name='votes_in_pokedex_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vote',
            name='pokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pokedex.pokemon'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='myuser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pokemon_created_by', related_query_name='pokemon_created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
