# Generated by Django 3.2.4 on 2021-07-15 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pokedex', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pokemon',
            options={'ordering': ['number', '-name'], 'verbose_name': 'Pokemon', 'verbose_name_plural': 'Pokemons'},
        ),
    ]
