### LOGIN WITH BASIC AUTHENTICATION
# @name loginUser
POST https://localhost:443/user/login
Authorization: Basic Ymxvb21AbWFpbC5kZToxMjM=

@bloomToken = {{loginUser.response.headers.Authorization}}

### CREATE AN HUB WITH JSON BODY
POST https://localhost:443/hub/addHub
Authorization: {{bloomToken}}
Content-Type: application/json

{
    "hub_id": 1,
    "bucket_empty": false,
    "outlet_count": 3,
    "factory_key": "1234543235349758432",
    "auto": false
}

### LOGIN AN HUB, GET TOKEN BACK AND CREATE USER_KEY IN HUB
# @name hubRegistration
POST https://localhost:443/hubRegistration/postHubRegistration
Authorization: Basic MToxMjM0NTQzMjM1MzQ5NzU4NDMy

@bloomHubToken = {{hubRegistration.response.headers.Authorization}}

### MAP USER WITH EMAIL TO HUB WITH USER_KEY
POST https://localhost:443/user/postUserKey
Authorization: {{bloomToken}}
Content-Type: application/json

{
    "user_key": 889993496,
    "email": "bloom@mail.de"
}


// ---------- Tests mit Server-Adresse ----------


### LOGIN WITH BASIC AUTHENTICATION
# @name loginUser
POST https://217.160.45.110:443/user/login
Authorization: Basic Ymxvb21AbWFpbC5kZToxMjM=

@bloomToken = {{loginUser.response.headers.Authorization}}
### CREATE AN HUB WITH JSON BODY
POST https://217.160.45.110:443/hub/addHub
Authorization: {{bloomToken}}
Content-Type: application/json

{
    "hub_id": 1,
    "bucket_empty": false,
    "outlet_count": 3,
    "factory_key": "1234543235349758432",
    "auto": false
}

### LOGIN AN HUB, GET TOKEN BACK AND CREATE USER_KEY IN HUB
# @name hubRegistration
POST https://217.160.45.110:443/hubRegistration/postHubRegistration
Authorization: Basic MzowLjA4NDU5NDY5MDMxMTA1NTM5


@bloomHubToken = {{hubRegistration.response.headers.Authorization}}

### MAP USER WITH EMAIL TO HUB WITH USER_KEY
POST https://217.160.45.110:443/user/postUserKey
Authorization: {{bloomToken}}
Content-Type: application/json

{
    "user_key": 889993496,
    "email": "bloom@mail.de"
}