# Generated by Django 3.2.2 on 2021-05-06 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ComputerGame', '0002_auto_20210506_1508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='games',
            old_name='FSK',
            new_name='USK',
        ),
    ]
