# Generated by Django 3.2.4 on 2021-07-15 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Items', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='myuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_in_comments_created_by', related_query_name='votes_in_comments_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rating',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Items.items'),
        ),
        migrations.AddField(
            model_name='rating',
            name='myuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='items',
            name='myuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_created_by', related_query_name='item_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Items.items'),
        ),
        migrations.AddField(
            model_name='comment',
            name='myuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
