# Generated by Django 3.2.2 on 2021-05-06 11:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('descriptionText', models.CharField(max_length=200)),
                ('genre', models.CharField(choices=[('s', 'sports'), ('h', 'shooters'), ('r', 'role playing'), ('p', 'party games')], max_length=1)),
                ('FSK', models.IntegerField()),
                ('creator', models.CharField(max_length=100)),
                ('createDate', models.DateTimeField(blank=True, default=datetime.date.today)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', related_query_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
                'ordering': ['name', '-genre'],
            },
        ),
    ]
